version: '3.4'

services:
  packageservice:
    image: ${DOCKER_REGISTRY-}packageservice
    build:
      context: .
      dockerfile: PackageService/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - sqldata
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=Asd@@123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"